{
 "title": "Energy",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Electricity_Normal", "query": "@Electricity_Normal@" },
   { "name": "Electricity_Dal", "query": "@Electricity_Dal@" },
   { "name": "Electricity_Return", "query": "@Electricity_Return@" },
   { "name": "Electricity_Delivery", "query": "@Electricity_Delivery@" },
   { "name": "Electricity_Tax_Zone1", "query": "@Electricity_Tax_Zone1@" },
   {
    "name": "Electricity_Tax_Surcharge_Zone1",
    "query": "@Electricity_Tax_Surcharge_Zone1@"
   },
   { "name": "Gas_Rate", "query": "@Gas_Rate@" },
   { "name": "Gas_Delivery_Cost", "query": "@Gas_Delivery_Cost@" },
   { "name": "Gas_Connection_Cost", "query": "@Gas_Connection_Cost@" },
   { "name": "Gas_Tax", "query": "@Gas_Tax@" },
   { "name": "Gas_Tax_Surcharge", "query": "@Gas_Tax_Surcharge@" },
   { "name": "Energy_Tax_Reduction", "query": "@Energy_Tax_Reduction@" }
  ]
 },
 "panels": [
  { "title": "Hourly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Usage Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "max(delta(energy_Gas_readings_0_Value_m3[1h])) * ($Gas_Rate + $Gas_Tax + $Gas_Tax_Surcharge) + ($Gas_Connection_Cost + $Gas_Delivery_Cost) / 24",
     "legendFormat": "Gas Cost"
    },
    {
     "expr": "max(delta(energy_Electricity_incoming_tariff2_kwh[1h])) * ($Electricity_Normal + $Electricity_Tax_Zone1 + $Electricity_Tax_Surcharge_Zone1) + max(delta(energy_Electricity_incoming_tariff1_kwh[1h])) * ($Electricity_Dal + $Electricity_Tax_Zone1 + $Electricity_Tax_Surcharge_Zone1) +($Electricity_Delivery - $Energy_Tax_Reduction ) / 24",
     "legendFormat": "Electricity Cost"
    },
    {
     "expr": "(max(delta(energy_Electricity_outgoing_tariff1_kwh[1h])) + max(delta(energy_Electricity_outgoing_tariff2_kwh[1h]))) * $Electricity_Return ",
     "legendFormat": "Electricity Cost"
    },
    { "expression": "$A + $C - $B", "type": "math" }
   ]
  },
  {
   "title": "Gas Usage HeatMap Per Hour",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "max(delta(energy_Gas_readings_0_Value_m3[1h])) * ($Gas_Rate + $Gas_Tax + $Gas_Tax_Surcharge) + ($Gas_Connection_Cost + $Gas_Delivery_Cost) / 24",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Electricity Usage HeatMap Per Hour",
   "type": "marcusolsson-hourly-heatmap-panel",
   "description": "Normal Rate is  0.08591/kWh\nDalTariff is 0.07405/kWh",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "max(delta(energy_Electricity_incoming_tariff2_kwh[1h])) * ($Electricity_Normal + $Electricity_Tax_Zone1 + $Electricity_Tax_Surcharge_Zone1) + max(delta(energy_Electricity_incoming_tariff1_kwh[1h])) * ($Electricity_Dal + $Electricity_Tax_Zone1 + $Electricity_Tax_Surcharge_Zone1) +($Electricity_Delivery - $Energy_Tax_Reduction ) / 24",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily Energy Costs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "expr": "max(delta(energy_Gas_readings_0_Value_m3[1d])) * ($Gas_Rate + $Gas_Tax + $Gas_Tax_Surcharge) + ($Gas_Connection_Cost + $Gas_Delivery_Cost)",
       "legendFormat": "Gas_Cost"
      },
      {
       "expr": "max(delta(energy_Electricity_incoming_tariff2_kwh[1d])) * ($Electricity_Normal + $Electricity_Tax_Zone1 + $Electricity_Tax_Surcharge_Zone1) + max(delta(energy_Electricity_incoming_tariff1_kwh[1d])) * ($Electricity_Dal + $Electricity_Tax_Zone1 + $Electricity_Tax_Surcharge_Zone1) +($Electricity_Delivery - $Energy_Tax_Reduction )",
       "legendFormat": "Electricity_Incoming_Cost"
      },
      {
       "expr": "(max(delta(energy_Electricity_outgoing_tariff1_kwh[1d])) + max(delta(energy_Electricity_outgoing_tariff2_kwh[1d]))) * $Electricity_Return ",
       "legendFormat": "Electricity_Outgoing_Cost"
      },
      { "expression": "$A + $B - $C", "type": "math" }
     ]
    },
    {
     "title": "Gas vs Electricity Cost Factor",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expression": "$A / ($B - $C)", "type": "math" }
     ]
    }
   ]
  }
 ]
}