# This Docker Compose only creates Smartmeter Reader and Sample MQTT Server.configs:
# The setup assumes that you have already setup of tools that can read messages from MQTT.configs:
# This is aimed at more advanced users.
version: '3'
services:
  smartmeter-reader:
    container_name: smartmeter-reader
    image: myrsh/smartmeter-reader
    restart: unless-stopped
    # user: "{{ user.uid }}:{{ user.gid }}"
    volumes:
      - ~/smartmeter-reader/config:/config:ro
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    network_mode: "host"
    depends_on: 
     - mosquitto
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001