on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release*' # Push events to matching release*, i.e. release-1.0, release-20.15.10, release-2020-10-28-10-26-15
    branches:
      - 'master'

name: Build Binary

jobs:
  build:
    name: Create Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Build Arm"
        id: build_arm
        run: ./build-arm.sh
      - name: "Build Linux"
        id: build_linux
        run: ./build-linux.sh
      - name: "Build Docker"
        id: build_docker
        run: "docker build -t myrsh/smartmeter-reader -f Dockerfile_arm . && docker login -u myrsh -p ${{ secrets.API_KEY_DOCKERHUB}} && docker push myrsh/smartmeter-reader"